development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: dat_orchestra_development
  pool:     5
  username: aleks
  password: ok
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: dat_orchestra_test
  pool:     5
  username: aleks
  password: ok
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: dat_orchestra_production
  pool:     5
  username: aleks
  password: ok
  template: template0
